baseURL = 'https://hugo-template-portfolio.app/'
title = 'Template de base'
enableEmoji = true
[params]
    dateFormat = "02 Jan 2006"

[menus]
  [[menus.header]]
    name = 'Accueil'
    url = '/'
    weight = 10
  [[menus.header]]
    name = 'Contact'
    url = '/contact'
    weight = 20
  [[menus.header]]
    name = 'Mes projets'
    url = '/projets'
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

defaultContentLanguage = 'fr'
[languages]
  [languages.fr]
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
  [languages.en]
    languageCode = 'en-EN'
    languageDirection = 'ltr'
    languageName = 'English'