baseURL = 'https://example.org/'
title = 'Template de base'
enableEmoji = true

[menus]
  [[menus.header]]
    name = 'Accueil'
    url = '/'
    weight = 10
  [[menus.header]]
    name = 'Contact'
    url = '/contact'
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

defaultContentLanguage = 'fr'
[languages]
  [languages.fr]
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
  [languages.en]
    languageCode = 'en-EN'
    languageDirection = 'ltr'
    languageName = 'English'